package model.IO;

public enum Errors {
    INVALID_PASSWORD,
    INVALID_USERNAME,
    WEAK_PASSWORD,
    USERNAME_ALREADY_TAKEN,
    WRONG_PASSWORD,
    REGISTERED,
    LOGGED_IN, USERNAME_NOT_FOUND,
    SAME_USERNAME,
    SAME_PASSWORD,
    INFO_CHANGED,
}
